# Generated by Django 3.0.2 on 2020-02-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(0, 'For parts'), (1, 'Used(normal wear)'), (2, 'Open Box (never used)'), (3, 'Reconditioned/Certified'), (4, 'New(never used)')], default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Los Angeles,Ca', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='cateogry',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Antique'), (2, 'Appliances'), (3, 'Arts & Crafts'), (4, 'Audio Equipment'), (5, 'Auto Parts'), (6, 'Baby & Kids'), (7, 'Beauty & Health'), (8, 'Bicycles'), (9, 'Boats and Marine'), (10, 'Books & Magazine'), (11, 'Business Equipment'), (12, 'Campers & RVs'), (13, 'Cars & Trucks'), (14, 'CDs & DVDs'), (15, 'Cell Phones'), (16, 'Clothing & Shoes'), (17, 'Collectables'), (18, 'Computer Equipment'), (19, 'Electronics'), (20, 'Musical Instruments'), (21, 'TVs'), (22, 'Video Games')], default=0),
        ),
    ]
