# Generated by Django 3.0.2 on 2020-02-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
