# Generated by Django 3.0.2 on 2020-02-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20200202_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=5, null=True),
        ),
    ]
