# Generated by Django 3.0.2 on 2020-02-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20200201_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(default='aT3Pws', max_length=6, unique=True),
        ),
    ]
