# Generated by Django 3.0.2 on 2020-02-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('cateogry', models.IntegerField(choices=[(0, 'Other'), (1, 'Antique'), (2, 'Appliances'), (3, 'Arts & Crafts'), (4, 'Audio Equipment'), (5, 'Auto Parts'), (6, 'Baby & Kids'), (7, 'Beauty & Health'), (8, 'Bicycles'), (9, 'Boats and Marine'), (10, 'Books & Magazine'), (11, 'Business Equipment'), (12, 'Campers & RVs'), (13, 'Cars & Trucks'), (14, 'CDs & DVDs'), (15, 'Cell Phones'), (16, 'Clothing & Shoes'), (17, 'Collectables'), (18, 'Computer Equipment'), (19, 'Electronics'), (20, 'Musical Instruments'), (21, 'Video Games')], default=0)),
            ],
        ),
    ]
