# Generated by Django 3.0.2 on 2020-02-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_auto_20200201_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
