# Generated by Django 3.0.2 on 2020-02-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default='BV1WFJMI', max_length=6, unique=True),
        ),
    ]
