# Generated by Django 3.0.2 on 2020-02-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0016_auto_20200201_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-title']},
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(default='M316JRHU', max_length=8, unique=True),
        ),
    ]
