# Generated by Django 3.0.2 on 2020-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_auto_20200201_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='hXw3zNFR', max_length=8, unique=True),
        ),
    ]
